baseURL = "https://maxime-cls.github.io/elastic-tutorial/"
title = "Elastic Tutoriel"
theme = "hugo-theme-learn"
languageCode = "fr-FR"
languageName = "Français"

[params]
themeVariant = "blue"
author = "Maxime Calves"
description = "Tutoriel sur Elastic"
showVisitedLinks = true
disableSearch = false
disableLandingPageButton = true

[outputs]
home = ["HTML", "RSS", "JSON"]
